update

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,87 +2,89 @@ name: Build Android Debug APK and Send Email
 
 on:
   push:
-    branches: [ dev ]
+    branches: [dev]
   pull_request:
-    branches: [ dev ]
+    branches: [dev]
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v4
+      - uses: actions/checkout@v4
 
-    - name: Set up JDK 17
-      uses: actions/setup-java@v3
-      with:
-        java-version: '17'
-        distribution: 'temurin'
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'temurin'
 
-    - name: Set up Node.js
-      uses: actions/setup-node@v4
-      with:
-        node-version: '18.x'
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: '18.x'
 
-    - name: Cache Gradle packages
-      uses: actions/cache@v3
-      with:
-        path: |
-          ~/.gradle/caches
-          ~/.gradle/wrapper
-        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
-        restore-keys: |
-          ${{ runner.os }}-gradle-
+      - name: Cache Gradle packages
+        uses: actions/cache@v3
+        with:
+          path: |
+            ~/.gradle/caches
+            ~/.gradle/wrapper
+          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
+          restore-keys: |
+            ${{ runner.os }}-gradle-
 
-    - name: Cache Android SDK
-      uses: actions/cache@v3
-      with:
-        path: ~/android/sdk
-        key: ${{ runner.os }}-android-sdk
-        restore-keys: ${{ runner.os }}-android-sdk
+      - name: Cache Android SDK
+        uses: actions/cache@v3
+        with:
+          path: ~/android/sdk
+          key: ${{ runner.os }}-android-sdk
+          restore-keys: ${{ runner.os }}-android-sdk
 
-    - name: Install dependencies
-      run: |
-        npm install
-        cd android
+      - name: Install dependencies
+        run: |
+          npm install
+          cd android
 
-    - name: Assemble Debug
-      run: |
-        cd android
-        ./gradlew assembleDebug
+      - name: Assemble Debug
+        run: |
+          cd android
+          ./gradlew assembleDebug
 
-    - name: Install jq
-      run: sudo apt-get update && sudo apt-get install jq
+      - name: Install jq
+        run: sudo apt-get update && sudo apt-get install jq
 
-    - name: Upload APK to File.io
-      id: upload_apk
-      run: |
-        RESPONSE=$(curl -F "file=@android/app/build/outputs/apk/debug/app-debug.apk" https://file.io)
-        UPLOAD_URL=$(echo "$RESPONSE" | jq -r '.link')
+      - name: Upload APK to File.io
+        id: upload_apk
+        run: |
+          UPLOAD_URL=$(echo "$RESPONSE" | jq -r '.link')
 
-        if [[ -z "$UPLOAD_URL" ]]; then
-          echo "::error title=File.io Upload Failed::Failed to upload APK to File.io. Response: $RESPONSE"
-          exit 1 # Fail the workflow
-        fi
+          if [[ -z "$UPLOAD_URL" ]]; then
+            echo "::error title=File.io Upload Failed::Failed to upload APK to File.io. Response: $RESPONSE"
+            exit 1 # Fail the workflow
+          fi
 
-        echo "apk_url=$UPLOAD_URL" >> $GITHUB_ENV
-        echo "APK uploaded to File.io.  URL: $UPLOAD_URL"
-      continue-on-error: false
+          echo "apk_url=$UPLOAD_URL" >> $GITHUB_ENV
+          echo "APK uploaded to File.io.  URL: $UPLOAD_URL"
+        continue-on-error: false
 
-    - name: Install sendEmail
-      run: |
-        sudo apt-get update
-        sudo apt-get install sendemail
+      - name: Install sendEmail
+        run: |
+          sudo apt-get update
+          sudo apt-get install sendemail
 
-    - name: Send Email with sendEmail
-      if: success()
-      run: |
-        sendEmail -f ${{ secrets.MAIL_USERNAME }} \
+      - name: Send Email with sendEmail
+        if: success()
+        run: |
+          APP_PASSWORD="ktut btyz bnmv xqwo"
+
+          sendEmail -f ${{ "Parthm@glorywebsdev.com" }} \
                   -t Parthm@glorywebsdev.com \
                   -s smtp.gmail.com:587 \
                   -xu ${{ secrets.MAIL_USERNAME }} \
-                  -xp ${{ secrets.MAIL_PASSWORD }} \
-                  -u "New Android Debug APK Build Available" \
-                  -m "A new Android Debug APK build is available for testing.\n\nYou can download the APK from File.io using the following link:\n${{ env.apk_url }}\n\n**Please note that File.io links are typically only valid for a single download.**\n\nWorkflow run URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-      shell: bash
+                  -xp "$APP_PASSWORD" \
+                  -v -v -v \ 
+                  -o tls=yes \ 
+                  -u "Test Email" \ 
+                  -m "This is a test email." 
+        shell: bash          
